apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mzyk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0046-tenant/tkrw-pr712-0075-0046-app/devfile-sample-mzyk@sha256:c0a243117c83550d559ea819a0260fd3459fa28a6ab67b3b2cd75ce194adf414
        name: my-nodejs
        resources: {}
status: {}
